DROP DATABASE IF EXISTS db_tdg;
CREATE DATABASE db_tdg;

CREATE TABLE admin( 
    id PRIMARY KEY AUTO_INCREMENT INTEGER NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    
    PRIMARY KEY (id)
)

CREATE TABLE categories (
    id PRIMARY KEY AUTO_INCREMENT TINYINT NOT NULL,
    name VARCHAR(100) NOT NULL, 
    color VARCHAR(100) NOT NULL,
    privileges VARCHAR(100) NOT NULL,

    PRIMARY KEY (id)
)

CREATE TABLE privileges (
    id PRIMARY KEY AUTO_INCREMENT TINYINT NOT NULL,
    privilege VARCHAR(150) NOT NULL,

    PRIMARY KEY (id)
)

CREATE TABLE products (
    id PRIMARY KEY AUTO_INCREMENT TINYINT NOT NULL,
    name VARCHAR(100) NOT NULL,
    privileges FOREIGN KEY NOT NULL,
    image IMAGE VARBINARY NOT NULL VARCHAR(250),
    min INTEGER NOT NULL,
    max INTEGER NOT NULL,
    category INTEGER NOT NULL FOREIGN KEY,
    range INTEGER NOT NULL,

    PRIMARY KEY (id)
)

CREATE TABLE users (
    id PRIMARY KEY AUTO_INCREMENT INTEGER NOT NULL,
    firstName VARCHAR(100) NOT NULL,
    lastName VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    birthDate DATE NOT NULL,
    adress VARCHAR(150) NOT NULL,
    phoneNumber BIGINT NOT NULL,
    country VARCHAR(100) NOT NULL,
    password VARCHAR(100) NOT NULL,
    passwordConfirm VARCHAR(100) NOT NULL,
    medioDePago VARCHAR(100) DEFAULT NULL,
    avatar IMAGE VARBINARY NOT NULL VARCHAR(250),

    PRIMARY KEY (id)
)